### PR TITLE
Feat/sqlite support

### PR DESCRIPTION
**Pull request by jeyren95**
Resolves https://github.com/chamanbravo/upstat/issues/34

**Changes made:**
1. Database
- removed pgcrypto from Postgres migration script
- added separate migration scripts for Postgres and Sqlite

2. API
- added sqlite connection as default
- used bcrypt to hash and salt passwords
- updated signing in, signing up and update password controllers to use bcrypt hashing

3. Docker
- updated Dockerfile to add sqlite support 
- added docker compose file for postgres users (default is sqlite)

**Tested on following platforms:**
1. Localhost
- [x] Migration scripts working
- [x] Sign up route
- [x] Sign in route
- [x] Update password route

2. Postgres docker
- [x] Sign up route
- [x] Sign in route
- [x] Update password route

3. Sqlite docker
- [x] Sign up route
- [x] Sign in route
- [x] Update password route

### CODE REVIEW

**Comment by yonas** [comment]
@chamanbravo Can we merge this?

**Comment by chamanbravo** [comment]
hello @yonas, thank you for the remainder, I will try to merge this asap.
Thank you @jeyren95 for your great work.

**Review by chamanbravo — CHANGES_REQUESTED** [review]
hello can you resolve the merge conflicts.
just pull from this branch: https://github.com/chamanbravo/upstat/tree/feat/sqlite-support
sorry took some time.

**Comment by jeyren95** [comment]
thanks for helping to resolve the conflict and merging to the main branch, was quite busy the past week so didnt have the time to look at it yet

**Comment by chamanbravo** [comment]
Its okay and thank you so much for your contributions.

**Pull request merged**
